version: "3.8"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: always
    depends_on:
      - zookeeper
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 4
  node-consumer:
    image: node:17
    volumes:
      - ./node-consumer:/app
    command: node /app/src/consume.js
    restart: always
    depends_on:
      - zookeeper
      - kafka
  php-consumer:
    build:
      context: .docker/php
    volumes:
      - ./php-consumer:/app
    command: php src/consume.php
    restart: always
    depends_on:
      - zookeeper
      - kafka
  go-consumer:
    build:
      context: .docker/go
    volumes:
      - ./go-consumer:/app
    command: ./go-consumer -brokers="kafka:9092" -topics="test-topic" -group="go-test-group"
    restart: always
    depends_on:
      - zookeeper
      - kafka  
  rust-consumer:
    build:
      context: .docker/rust
    volumes:
      - ./rust-consumer:/app
    command: ./rust-consumer --brokers="kafka:9092" --topics="test-topic" --group="rust-test-group"
    restart: always
    depends_on:
      - zookeeper
      - kafka
  rust-gateway:
    build:
      context: .docker/rust
    volumes:
      - ./rust-gateway:/app
    command: ./rust-gateway --brokers="kafka:9092" --topics="test-topic" --group="rust-test-group"
    ports:
      - 7777:7777
    restart: always
    depends_on:
      - zookeeper
      - kafka
  node-producer:
    image: node:17
    volumes:
      - ./node-producer:/app
    command: node /app/src/produce.js
    restart: always
    depends_on:
      - zookeeper
      - kafka
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
